// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"github.com/TemaKut/messenger/internal/services/auth/internal/app/config"
	"github.com/TemaKut/messenger/internal/services/auth/transport/grpc/auth"
)

// Injectors from wire.go:

func InitService() (*App, func(), error) {
	configConfig := config.NewConfig()
	logger, err := ProvideLogger(configConfig)
	if err != nil {
		return nil, nil, err
	}
	server, cleanup, err := ProvideGRPCServer(logger, configConfig)
	if err != nil {
		return nil, nil, err
	}
	service := auth.NewService()
	authService := ProvideAuthService(server, service)
	grpcProvider := ProvideGRPC(authService)
	app, cleanup2 := ProvideApp(logger, grpcProvider)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
