// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"my_project/internal/app"
)

// Injectors from wire.go:

func InitApp() (*app.App, func(), error) {
	appApp, cleanup := app.NewApp()
	return appApp, func() {
		cleanup()
	}, nil
}
