// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"context"
	"github.com/TemaKut/messenger/internal/services/apigateway/internal/app"
	"github.com/TemaKut/messenger/internal/services/apigateway/internal/config"
)

// Injectors from wire.go:

func InitApp(ctx context.Context, cfg *config.Config) (*app.App, func(), error) {
	appApp := app.NewApp()
	return appApp, func() {
	}, nil
}
