// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"context"
	"github.com/TemaKut/messenger/internal/services/apigateway/internal/app"
	kafka2 "github.com/TemaKut/messenger/internal/services/apigateway/internal/clients/broker/kafka"
	"github.com/TemaKut/messenger/internal/services/apigateway/internal/config"
	"github.com/TemaKut/messenger/internal/services/apigateway/internal/logger"
	"github.com/TemaKut/messenger/internal/services/apigateway/pkg/transport/broker/kafka"
	"github.com/TemaKut/messenger/internal/services/apigateway/pkg/transport/websocket"
)

// Injectors from wire.go:

func InitApp(ctx context.Context, cfg *config.Config) (*app.App, func(), error) {
	slogLogger, err := logger.NewLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	websocketServer := websocket.NewWebsocketServer(cfg, slogLogger)
	serviceHandler := kafka.NewServiceHandler(slogLogger)
	topicBuilder := ProvideTopicBuilder()
	serviceConsumer, err := kafka2.NewServiceConsumer(cfg, serviceHandler, topicBuilder)
	if err != nil {
		return nil, nil, err
	}
	appApp := app.NewApp(websocketServer, serviceConsumer, slogLogger)
	return appApp, func() {
	}, nil
}
