// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"github.com/TemaKut/messenger/internal/services/apigateway/internal/app/config"
	"github.com/TemaKut/messenger/internal/services/apigateway/internal/service/session"
)

// Injectors from wire.go:

func InitService() (*App, func(), error) {
	configConfig := config.NewConfig()
	logger, err := ProvideLogger(configConfig)
	if err != nil {
		return nil, nil, err
	}
	authServiceClient, cleanup, err := ProvideAuthServiceGRPCClient(logger, configConfig)
	if err != nil {
		return nil, nil, err
	}
	sessionService := session.NewSesionService(logger, authServiceClient)
	httpServerProvider, cleanup2, err := ProvideHttpServer(configConfig, logger, sessionService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app, cleanup3 := ProvideApp(logger, httpServerProvider)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
